server:
  port: 8080

spring:
  datasource:
      name: master
      url: jdbc:mysql://localhost:3306/ds_0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root1234


